=== ivamsi2001/MyExamples/jaxb-xsd-example/src/main/resources/employee.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.venkat.com/Employee" 
	xmlns:empns3="http://www.venkat.com/Employee">

	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1" />
				<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="salary" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="designation" type="xs:string" minOccurs="0" maxOccurs="1" />
				<xs:element name="addressList" type="empns3:addressList"	minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="addressList">
		<xs:sequence>
			<xs:element name="address" type="empns3:address" minOccurs="1" maxOccurs="5" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="address">
		<xs:sequence>
			<xs:element name="city" type="xs:string" minOccurs="1" />
			<xs:element name="line1" type="xs:string" minOccurs="1" />
			<xs:element name="line2" type="xs:string" minOccurs="0" />
			<xs:element name="state" type="xs:string" minOccurs="0" />
			<xs:element name="zipcode" type="xs:long" />
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required" />
	</xs:complexType>
</xs:schema>

=== ivamsi2001/MyExamples/jaxb-xsd-example/src/main/resources/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<empns:employee xmlns:empns="http://www.venkat.com/Employee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.venkat.com/Employee employee.xsd ">

	<id>007</id>
	<name>Venkat</name>
	<salary>100000000</salary>
	<designation>JA</designation>
	<addressList>
		<address type="Main">
			<city>Hyderabad</city>
			<line1>line1</line1>
			<line2>line2</line2>
			<state>TS</state>
			<zipcode>0</zipcode>
		</address>
		<address type="Main">
			<city>Hyderabad</city>
			<line1>line1</line1>
			<line2>line2</line2>
			<state>TS</state>
			<zipcode>0</zipcode>
		</address>
	</addressList>
</empns:employee>
